service: dr-tiedonkeruu
frameworkVersion: '3'

useDotenv: true

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-s3-sync

custom:
  s3Sync:
    - bucketNameKey: FrontendS3BucketNameOutputKey
      localDir: ui
      deleteRemoved: true

package:
  individually: true

provider:
  name: aws
  runtime: nodejs16.x
  region: ${env:REGION}
  vpc:
    securityGroupIds:
      - ${env:VPC_SECURITY_GROUP_ID}
    subnetIds:
      - ${env:VPC_SUBNET_ID_1}
      - ${env:VPC_SUBNET_ID_2}
  httpApi:
    cors: true
  iam:
    deploymentRole: arn:aws:iam::${env:AWS_ACCOUNT_ID}:role/dr-tiedonkeruu-CloudFormationExecutionRole
    role:
      statements:
        - Effect: Allow
          Action:
            - ses:SendEmail
            - ses:SendRawEmail
            - ses:SendTemplatedEmail
          Resource: '*'

functions:
  handlePost:
    handler: src/handler.handlePost
    events:
      - httpApi:
          path: /postData
          method: post

resources:
  Resources:
    FrontendS3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: dr-tiedonkeruu-${env:STAGE_NAME}-frontend-hosting

    FrontendS3OAI:
      Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
      Properties:
        CloudFrontOriginAccessIdentityConfig:
          Comment: 'DRTiedonkeruu Frontend Origin Access Identity'

    FrontendS3BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: FrontendS3Bucket
        PolicyDocument:
          Statement:
            - Effect: Allow
              Principal:
                CanonicalUser:
                  Fn::GetAtt:
                    - FrontendS3OAI
                    - S3CanonicalUserId
              Action: s3:GetObject
              Resource:
                Fn::Join:
                  - ''
                  - - 'arn:aws:s3:::'
                    - !Ref FrontendS3Bucket
                    - '/*'

    CloudFrontDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Origins:
            - Id: S3Origin
              DomainName:
                Fn::Join:
                  - ''
                  - - !Ref FrontendS3Bucket
                    - '.s3-${env:REGION}.amazonaws.com'
              S3OriginConfig:
                OriginAccessIdentity: !Sub 'origin-access-identity/cloudfront/${FrontendS3OAI}'
          DefaultRootObject: index.html
          DefaultCacheBehavior:
            TargetOriginId: S3Origin
            CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
            ViewerProtocolPolicy: https-only
          Enabled: true

  Outputs:
    FrontendS3BucketNameOutputKey:
      Value: !Ref FrontendS3Bucket
