service: dr-tiedonkeruu-waf
frameworkVersion: '3'

useDotenv: true

custom:
  stage: ${opt:stage, 'dev'}

package:
  individually: true

provider:
  name: aws
  stage: ${self:custom.stage}
  region: us-east-1
  iam:
    deploymentRole: arn:aws:iam::${env:AWS_ACCOUNT_ID}:role/${env:AWS_CLOUDFORMATION_ROLE}

resources:
  Resources:
    CloudFrontWebACL:
      Type: AWS::WAFv2::WebACL
      Properties:
        Name: dr-tiedonkeruu-${self:custom.stage}-waf
        Description: 'DRTiedonkeruu WAF Configuration'
        DefaultAction:
          Allow: {}
        Rules:
          - Name: RateBasedRule-IP-300
            Priority: 0
            Statement:
              RateBasedStatement:
                Limit: 300
                AggregateKeyType: IP
            Action:
              Count: {}
            VisibilityConfig:
              CloudWatchMetricsEnabled: true
              MetricName: RateBasedRule-IP-300
              SampledRequestsEnabled: true
        Scope: CLOUDFRONT
        VisibilityConfig:
          CloudWatchMetricsEnabled: true
          MetricName: dr-tiedonkeruu-${self:custom.stage}-waf
          SampledRequestsEnabled: true

  Outputs:
    WebACLId:
      Value: !Ref CloudFrontWebACL