service: dr-tiedonkeruu
frameworkVersion: '3'

useDotenv: true

plugins:
  - serverless-plugin-typescript
  - serverless-offline

package:
  individually: true

provider:
  name: aws
  runtime: nodejs16.x
  region: ${env:REGION}
  iam:
    deploymentRole: arn:aws:iam::${env:AWS_ACCOUNT_ID}:role/dr-tiedonkeruu-CloudFormationExecutionRole
  vpc:
    securityGroupIds:
      - ${env:VPC_SECURITY_GROUP_ID}
    subnetIds:
      - ${env:VPC_SUBNET_ID_1}
      - ${env:VPC_SUBNET_ID_2}

resources:
  Resources:
    FrontendS3Bucket:
      Type: AWS::S3::Bucket
