service: dr-tiedonkeruu
frameworkVersion: '3'

useDotenv: true

plugins:
  - serverless-plugin-typescript
  - serverless-iam-roles-per-function
  - serverless-s3-local
  - serverless-offline
  - serverless-s3-sync

custom:
  stage: ${opt:stage, 'dev'}
  serverless-offline:
    httpPort: 3003
  s3: # serverless-s3-local configuration
    address: 127.0.0.1
    directory: ./s3rver
  securityGroupId: ${env:offline.SECURITY_GROUP_ID, ssm:${env:SECURITY_GROUP_ID}}
  subnetId1: ${env:offline.SUBNET_ID_1, ssm:${env:SUBNET_ID_1}}
  subnetId2: ${env:offline.SUBNET_ID_2, ssm:${env:SUBNET_ID_2}}
  recaptchaSecret: ${env:offline.RECAPTCHA_SECRET, ssm:${env:RECAPTCHA_SECRET}}
  virusScanBucket: dr-tiedonkeruu-${self:custom.stage}-virus-scanner-hosting
  virusScanLambda: ${env:offline.VIRUS_SCAN_LAMBDA, ssm:${env:VIRUS_SCAN_LAMBDA}}
  virusScanRole: ${env:offline.VIRUS_SCAN_ROLE, ssm:${env:VIRUS_SCAN_ROLE}}
  s3Sync:
    - bucketNameKey: FrontendS3BucketName
      localDir: ui
      deleteRemoved: true

package:
  individually: true

provider:
  name: aws
  stage: ${self:custom.stage}
  runtime: nodejs18.x
  region: ${env:REGION}
  vpc:
    securityGroupIds:
      - ${self:custom.securityGroupId}
    subnetIds:
      - ${self:custom.subnetId1}
      - ${self:custom.subnetId2}
  httpApi:
    metrics: true
    shouldStartNameWithService: true
    cors:
      allowedOrigins:
        - "*" # REMOVE THIS IN PRODUCTION
        - ${env:FRONTEND_URL}
      allowedHeaders:
        - g-recaptcha-response
      allowedMethods:
        - OPTIONS
        - POST
  iam:
    deploymentRole: arn:aws:iam::${env:AWS_ACCOUNT_ID}:role/${env:AWS_CLOUDFORMATION_ROLE}

functions:
  handlePost:
    handler: src/postLambda.handler
    iamRoleStatements:
      - Effect: Allow
        Action:
          - s3:PutObject
        Resource:
          - arn:aws:s3:::${self:custom.virusScanBucket}
          - arn:aws:s3:::${self:custom.virusScanBucket}/*
    environment:
      RECAPTCHA_SECRET: ${self:custom.recaptchaSecret}
      VIRUS_SCAN_BUCKET: ${self:custom.virusScanBucket}
    events:
      - httpApi:
          path: /postData
          method: post

  sendEmail:
    handler: src/emailLambda.handler
    iamRoleStatements:
      - Effect: Allow
        Action:
          - ssm:GetParameter
          - ssm:GetParameters
        Resource:
          - arn:aws:ssm:${env:REGION}:${env:AWS_ACCOUNT_ID}:parameter/${env:SMTP_CREDENTIALS_NAME}
      - Effect: Allow
        Action:
          - s3:ListBucket
          - s3:GetObject
          - s3:GetObjectTagging
          - s3:DeleteObject
        Resource:
          - arn:aws:s3:::${self:custom.virusScanBucket}
          - arn:aws:s3:::${self:custom.virusScanBucket}/*
    environment:
      REGION: ${env:REGION}
      SMTP_CREDENTIALS_NAME: ${env:SMTP_CREDENTIALS_NAME}
      SMTP_ENDPOINT: email-smtp.${env:REGION}.amazonaws.com
      SMTP_SENDER: ${env:SMTP_SENDER}
      VIRUS_SCAN_BUCKET: ${self:custom.virusScanBucket}

resources:
  Resources:
    HandlePostLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        RetentionInDays: 180

    SendEmailLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        RetentionInDays: 180

    DrTiedonkeruuAlarmTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: DrTiedonkeruuAlarmTopic

    HandlePostInvocationAlarm:
      Type: AWS::CloudWatch::Alarm
      Properties:
        AlarmName: DrTiedonkeruu/HandlePostInvocationAlarm
        AlarmDescription: Alarm for unusually high number of invocations of HandlePost
        MetricName: Invocations
        Namespace: AWS/Lambda
        Statistic: Sum
        Period: 300 # 5 minutes
        EvaluationPeriods: 3
        DatapointsToAlarm: 2
        Threshold: 1000
        ComparisonOperator: GreaterThanThreshold
        TreatMissingData: notBreaching
        Dimensions:
          - Name: FunctionName
            Value: ${self:service}-${self:custom.stage}-handlePost
        AlarmActions:
          - !Ref DrTiedonkeruuAlarmTopic

    S3BucketDrtiedonkeruudevvirusscannerhosting:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.virusScanBucket}
        NotificationConfiguration:
          LambdaConfigurations:
            - Event: s3:ObjectCreated:*
              Function: ${self:custom.virusScanLambda} # Needs S3BucketDrtiedonkeruudevvirusscannerhostingPolicy
            - Event: s3:ObjectTagging:Put # Needs InvokeSendEmailPermissionVirusScanS3
              Function:
                Fn::GetAtt:
                  - SendEmailLambdaFunction
                  - Arn

    S3BucketDrtiedonkeruudevvirusscannerhostingPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: S3BucketDrtiedonkeruudevvirusscannerhosting
        PolicyDocument:
          Statement:
            - Effect: Allow
              Principal:
                AWS: ${self:custom.virusScanRole}
              Action:
                - s3:GetObject
                - s3:PutObjectTagging
              Resource:
                Fn::Join:
                  - ''
                  - - 'arn:aws:s3:::'
                    - !Ref S3BucketDrtiedonkeruudevvirusscannerhosting
                    - '/*'

    InvokeSendEmailPermissionVirusScanS3:
      Type: AWS::Lambda::Permission
      Properties:
        FunctionName:
          Fn::GetAtt:
            - SendEmailLambdaFunction
            - Arn
        Action: lambda:InvokeFunction
        Principal: s3.amazonaws.com
        SourceArn:
          Fn::Join:
            - ''
            - - 'arn:'
              - Ref: AWS::Partition
              - ':s3:::dr-tiedonkeruu-dev-virus-scanner-hosting'
        SourceAccount:
          Ref: AWS::AccountId

    FrontendS3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: dr-tiedonkeruu-${self:custom.stage}-frontend-hosting

    FrontendS3OAI:
      Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
      Properties:
        CloudFrontOriginAccessIdentityConfig:
          Comment: 'DRTiedonkeruu Frontend Origin Access Identity'

    FrontendS3BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: FrontendS3Bucket
        PolicyDocument:
          Statement:
            - Effect: Allow
              Principal:
                CanonicalUser:
                  Fn::GetAtt:
                    - FrontendS3OAI
                    - S3CanonicalUserId
              Action: s3:GetObject
              Resource:
                Fn::Join:
                  - ''
                  - - 'arn:aws:s3:::'
                    - !Ref FrontendS3Bucket
                    - '/*'

    CloudFrontDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Origins:
            - Id: S3Origin
              DomainName:
                Fn::Join:
                  - ''
                  - - !Ref FrontendS3Bucket
                    - '.s3-${env:REGION}.amazonaws.com'
              S3OriginConfig:
                OriginAccessIdentity: !Sub 'origin-access-identity/cloudfront/${FrontendS3OAI}'
            - Id: ApiGatewayOrigin
              DomainName:
                Fn::Join:
                  - ''
                  - - !Ref HttpApi
                    - '.execute-api.${env:REGION}.amazonaws.com'
              OriginPath: /api
              CustomOriginConfig:
                OriginProtocolPolicy: https-only
                OriginSSLProtocols:
                  - TLSv1.2
          DefaultRootObject: index.html
          DefaultCacheBehavior:
            TargetOriginId: S3Origin
            CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6 # Managed-CachingOptimized
            ViewerProtocolPolicy: https-only
          CacheBehaviors:
            - TargetOriginId: ApiGatewayOrigin
              PathPattern: /api
              ViewerProtocolPolicy: https-only
              CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad # Managed-CachingDisabled
              AllowedMethods:
                - GET
                - HEAD
                - OPTIONS
                - PUT
                - PATCH
                - POST
                - DELETE
          Enabled: true

  Outputs:
    FrontendS3BucketName:
      Description: 'Name of the frontend S3 bucket'
      Value: !Ref FrontendS3Bucket
    CloudFrontDistributionUrl:
      Description: 'URL of the CloudFront distribution for the frontend'
      Value:
        Fn::Join:
          - ''
          - - 'https://'
            - !GetAtt CloudFrontDistribution.DomainName
