service: dr-tiedonkeruu
frameworkVersion: '3'

useDotenv: true

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-s3-sync

custom:
  stage: ${opt:stage, 'dev'}
  serverless-offline:
    httpPort: 3003
  securityGroupId: ${env:offline.SECURITY_GROUP_ID, ssm:${env:SECURITY_GROUP_ID}}
  subnetId1: ${env:offline.SUBNET_ID_1, ssm:${env:SUBNET_ID_1}}
  subnetId2: ${env:offline.SUBNET_ID_2, ssm:${env:SUBNET_ID_2}}
  recaptchaSecret: ${env:offline.RECAPTCHA_SECRET, ssm:${env:RECAPTCHA_SECRET}}
  s3Sync:
    - bucketNameKey: FrontendS3BucketNameOutputKey
      localDir: ui
      deleteRemoved: true

package:
  individually: true

provider:
  name: aws
  stage: ${self:custom.stage}
  runtime: nodejs16.x
  region: ${env:REGION}
  vpc:
    securityGroupIds:
      - ${self:custom.securityGroupId}
    subnetIds:
      - ${self:custom.subnetId1}
      - ${self:custom.subnetId2}
  httpApi:
    cors:
      allowedOrigins:
        - ${env:FRONTEND_URL}
      allowedHeaders:
        - g-recaptcha-response
      allowedMethods:
        - OPTIONS
        - POST
  iam:
    deploymentRole: arn:aws:iam::${env:AWS_ACCOUNT_ID}:role/${env:AWS_CLOUDFORMATION_ROLE}

functions:
  handlePost:
    handler: src/handler.handlePost
    environment:
      RECAPTCHA_SECRET: ${self:custom.recaptchaSecret}
      REGION: ${env:REGION}
      SMTP_CREDENTIALS_NAME: ${env:SMTP_CREDENTIALS_NAME}
      SMTP_ENDPOINT: email-smtp.${env:REGION}.amazonaws.com
      SMTP_SENDER: ${env:SMTP_SENDER}
    events:
      - httpApi:
          path: /postData
          method: post
    iamRoleStatements:
      - Effect: Allow
        Action:
          - ssm:GetParameter
          - ssm:GetParameters
        Resource:
          - arn:aws:ssm:${env:REGION}:${env:AWS_ACCOUNT_ID}:parameter/${env:SMTP_CREDENTIALS_NAME}

  sendEmail:
    handler: src/handler.sendEmail
    events:
      - s3:
          bucket: dr-tiedonkeruu-${self:custom.stage}-virus-scanner-hosting
          event: s3:ObjectCreated:* # Trigger Lambda function when a new file is uploaded to the S3 bucket
      - schedule: cron(0 6 ? * MON-FRI *) # Trigger Lambda function every weekday at 8:00 AM UTC+2
      - schedule: cron(0 9 ? * MON-FRI *) # Trigger Lambda function every weekday at 11:00 AM UTC+2
      - schedule: cron(0 12 ? * MON-FRI *) # Trigger Lambda function every weekday at 2:00 PM UTC+2
    iamRoleStatements:
      - Effect: Allow
        Action:
          - s3:ListBucket
          - s3:GetObject
        Resource:
          - arn:aws:s3:::dr-tiedonkeruu-${self:custom.stage}-frontend-hosting
          - arn:aws:s3:::dr-tiedonkeruu-${self:custom.stage}-frontend-hosting/*

resources:
  Resources:
    HandlePostLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        RetentionInDays: 180

    FrontendS3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: dr-tiedonkeruu-${self:custom.stage}-frontend-hosting

    FrontendS3OAI:
      Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
      Properties:
        CloudFrontOriginAccessIdentityConfig:
          Comment: 'DRTiedonkeruu Frontend Origin Access Identity'

    FrontendS3BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: FrontendS3Bucket
        PolicyDocument:
          Statement:
            - Effect: Allow
              Principal:
                CanonicalUser:
                  Fn::GetAtt:
                    - FrontendS3OAI
                    - S3CanonicalUserId
              Action: s3:GetObject
              Resource:
                Fn::Join:
                  - ''
                  - - 'arn:aws:s3:::'
                    - !Ref FrontendS3Bucket
                    - '/*'

    CloudFrontDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Origins:
            - Id: S3Origin
              DomainName:
                Fn::Join:
                  - ''
                  - - !Ref FrontendS3Bucket
                    - '.s3-${env:REGION}.amazonaws.com'
              S3OriginConfig:
                OriginAccessIdentity: !Sub 'origin-access-identity/cloudfront/${FrontendS3OAI}'
          DefaultRootObject: index.html
          DefaultCacheBehavior:
            TargetOriginId: S3Origin
            CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
            ViewerProtocolPolicy: https-only
          Enabled: true

  Outputs:
    FrontendS3BucketNameOutputKey:
      Value: !Ref FrontendS3Bucket
