service: dr-tiedonkeruu
frameworkVersion: '3'

useDotenv: true

plugins:
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  runtime: nodejs16.x
  region: ${env:REGION}
  vpc:
    securityGroupIds:
      - ${env:VPC_SECURITY_GROUP_ID}
    subnetIds:
      - ${env:VPC_SUBNET_ID_1}
      - ${env:VPC_SUBNET_ID_2}

functions:
  ping:
    handler: src/handler.ping
    events:
      - httpApi:
          path: /ping
          method: get
  handlePost:
    handler: src/handler.handlePost
    events:
      - httpApi:
          path: /postData
          method: post

resources:
  Resources:
    FrontendS3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: dr-tiedonkeruu-${env:STAGE_NAME}-frontend-hosting-bucket
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: error.html

    CloudFrontDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Origins:
            - DomainName: dr-tiedonkeruu-${env:STAGE_NAME}-frontend-hosting-bucket.s3.${env:REGION}.amazonaws.com
              Id: S3Origin
              CustomOriginConfig:
                OriginProtocolPolicy: https-only
          DefaultCacheBehavior:
            TargetOriginId: S3Origin
            ViewerProtocolPolicy: https-only
          Enabled: true
