service: dr-tiedonkeruu
frameworkVersion: '3'

useDotenv: true

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-s3-sync

custom:
  s3Sync:
    - bucketNameKey: FrontendS3BucketNameOutputKey
      localDir: ui
      deleteRemoved: true

package:
  individually: true

provider:
  name: aws
  stage: ${env:STAGE_NAME}
  runtime: nodejs16.x
  region: ${env:REGION}
  vpc:
    securityGroupIds:
      - ${ssm:${env:SECURITY_GROUP_ID}}
    subnetIds:
      - ${ssm:${env:SUBNET_ID_1}}
      - ${ssm:${env:SUBNET_ID_2}}
  httpApi:
    cors:
      allowedOrigins:
        - ${env:FRONTEND_URL}
      allowedHeaders:
        - g-recaptcha-response
      allowedMethods:
        - OPTIONS
        - POST
  iam:
    deploymentRole: arn:aws:iam::${AWS::AccountId}:role/dr-tiedonkeruu-CloudFormationExecutionRole
    role:
      statements:
        - Effect: Allow
          Action:
            - ssm:GetParameter
            - ssm:GetParameters
          Resource:
            - arn:aws:ssm:${env:REGION}:${AWS::AccountId}:parameter/${env:SMTP_CREDENTIALS_NAME}

functions:
  handlePost:
    handler: src/handler.handlePost
    environment:
      RECAPTCHA_SECRET: ${ssm:${env:RECAPTCHA_SECRET}}
      REGION: ${env:REGION}
      SMTP_CREDENTIALS_NAME: ${env:SMTP_CREDENTIALS_NAME}
      SMTP_ENDPOINT: email-smtp.${env:REGION}.amazonaws.com
      SMTP_SENDER: ${env:SMTP_SENDER}
    events:
      - httpApi:
          path: /postData
          method: post

resources:
  Resources:
    FrontendS3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: dr-tiedonkeruu-${env:STAGE_NAME}-frontend-hosting

    FrontendS3OAI:
      Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
      Properties:
        CloudFrontOriginAccessIdentityConfig:
          Comment: 'DRTiedonkeruu Frontend Origin Access Identity'

    FrontendS3BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: FrontendS3Bucket
        PolicyDocument:
          Statement:
            - Effect: Allow
              Principal:
                CanonicalUser:
                  Fn::GetAtt:
                    - FrontendS3OAI
                    - S3CanonicalUserId
              Action: s3:GetObject
              Resource:
                Fn::Join:
                  - ''
                  - - 'arn:aws:s3:::'
                    - !Ref FrontendS3Bucket
                    - '/*'

    CloudFrontDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Origins:
            - Id: S3Origin
              DomainName:
                Fn::Join:
                  - ''
                  - - !Ref FrontendS3Bucket
                    - '.s3-${env:REGION}.amazonaws.com'
              S3OriginConfig:
                OriginAccessIdentity: !Sub 'origin-access-identity/cloudfront/${FrontendS3OAI}'
          DefaultRootObject: index.html
          DefaultCacheBehavior:
            TargetOriginId: S3Origin
            CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
            ViewerProtocolPolicy: https-only
          Enabled: true

  Outputs:
    FrontendS3BucketNameOutputKey:
      Value: !Ref FrontendS3Bucket
