service: dr-tiedonkeruu
frameworkVersion: '3'

useDotenv: true

plugins:
  - serverless-plugin-typescript
  - serverless-offline

package:
  individually: true

provider:
  name: aws
  runtime: nodejs16.x
  region: ${env:REGION}
  vpc:
    securityGroupIds:
      - ${env:VPC_SECURITY_GROUP_ID}
    subnetIds:
      - ${env:VPC_SUBNET_ID_1}
      - ${env:VPC_SUBNET_ID_2}
  httpApi:
    cors: true
  iam:
    deploymentRole: arn:aws:iam::${env:AWS_ACCOUNT_ID}:role/dr-tiedonkeruu-CloudFormationExecutionRole

functions:
  handlePost:
    handler: src/handler.handlePost
    events:
      - httpApi:
          path: /post
          method: post

resources:
  Resources:
    FrontendS3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: dr-tiedonkeruu-${env:STAGE_NAME}-frontend-hosting
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: error.html

    CloudFrontDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Origins:
            - Id: S3Origin
              DomainName: dr-tiedonkeruu-${env:STAGE_NAME}-frontend-hosting.s3-${env:REGION}.amazonaws.com
              CustomOriginConfig:
                OriginProtocolPolicy: https-only
          DefaultRootObject: index.html
          DefaultCacheBehavior:
            TargetOriginId: S3Origin
            CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
            ViewerProtocolPolicy: https-only
          Enabled: true
