name: Deploy development build to AWS

on:
  push:
    branches:
      - development

permissions:
  id-token: write
  contents: read
jobs:
  devDeployment:
    name: development deploy
    runs-on: ubuntu-latest
    environment:
      name: development
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build UI
        run: npm run build:ui
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOYMENT_ROLE }}
          role-session-name: ServerlessDeployment
          aws-region: ${{ secrets.REGION }}
      - name: Install serverless globally
        run: npm i -g serverless@3.x
      - name: Deploy to AWS
        run: npm run deploy:serverless
        env:
          REGION: ${{ secrets.REGION }}
          STAGE_NAME: ${{ secrets.STAGE_NAME }}
          VPC_SECURITY_GROUP_ID: ${{ secrets.VPC_SECURITY_GROUP_ID }}
          VPC_SUBNET_ID_1: ${{ secrets.VPC_SUBNET_ID_1 }}
          VPC_SUBNET_ID_2: ${{ secrets.VPC_SUBNET_ID_2 }}
